# assignment
1)task.py:-
here the compiler takes input of two numbers.
Then it displays the addition, subtraction, multiplication and division of the two numbers.

2)task-2.py:-
here the compiler takes the first and last name of the user individualy.
Then it uses the names and display a message hoping that the user is ready to learn more python.

3)task1-assignment-2:-
here the compiler takes in a  number from the user.
The compiler then test the condition if the number when divided by 2 gives zero or not.If True then the if statment(" number is an even number ") is printed. If False then the else statement("number is an odd number") is printed.

4)task2-assignment-2:-
here the compiler takes in an number from the user.
The compiler then applies a for loop from the range 0 to a+1. Here first the condition is checkedif the condition is true then the number is added to the sum. then 1 is added to that number and then the new number is used to check the condition if satisified then the loop repeats till a then when the new number becomes a+1 it exits the loop. Then using this sum we print the  sum.

5)task1-assignment-3:-
here the compiler accepts a value from user and then. here reccursion is the concept used to find the factoril.

6)task2-assignment-3:-
here the compiler imports math module then use them to to find the square root,natural log and sine of thethe input value from the user.

7)task1-assigment-5:-
here the dictionary is first created with the names of students as the key and marks as value. Then the name is accepted from the user.then the compiler search for the exact value. if codition is applied to check wheater the name exists if yes then the marks of the student is printed.else the compiler prints that the data does not exist in the record.

8)task2-assignment-5:-
here the list is created and then using this list a new list is extracted.The new extracted list is then copied to a new reverse_list and the list is then reversed.
the lists are then printed/displayed to the user

9)task1-assignment-4:-
here we use try block to check if any exception occurs...if yes then we use excpt <error/exception type>: and the error message to be printed
then we use finally block to explain what is this exception about.
here in try block we open,read and close the file.we open the sample.txt file, then read from the file and print the same for the user and later close the file.

10)task2-assignment-4:-
first we open a file"output.txt"in write mode add some data through f.write(text) and then close the file
then we again open the file in append mode and the data entered from the user is add to the file and then the file is closed
later again the file is opened in read mode and the data is extracted from file and printed to the user to see then the the file is closed..
